meta_title: "MesMidis - Déjeuner autrement"
meta_description: "Offrez-vous le resto chaque midi pour 6 €"
meta_image: "facebook.png" # should exist in `app/assets/images/`
twitter_account: "@mesmidis" # required for Twitter Cards
